Bai4/Bài 4.4/Bai4.4/Bai4.4/Models/NhanVien.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Bai4._4.Models
{
    public class NhanVien

    {
        public String MaNV { get; set; }
        public int NgayCong { get; set; }
        public int BacLuong { get; set; }
        public String ChucVu { get; set; }
        public double TienLinh { get; set; }
    }
}

Bai4/Bài 4.4/Bai4.4/Bai4.4/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Bai4._4.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Bai4/Bài 4.4/Bai4.4/Bai4.4/Controllers/NhanVienController.cs
using Bai4._4.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Bai4._4.Controllers
{
    public class NhanVienController : Controller
    {
        // GET: NhanVien
        public ActionResult Index()
        {
            return View();
        }
        public int NCTL(NhanVien nv)
        {
            int i = 0;

            if (nv.NgayCong < 25)
            {
                i = nv.NgayCong;
            }
            else
            {
                i = (nv.NgayCong - 25) * 2 + 25;
            }
            return i;
        }
        public double PhuCap(NhanVien nv)
        {
            double phucap = 0;
            if(nv.ChucVu =="Trưởng phòng")
            {
                phucap = 500000;
            }
            else if(nv.ChucVu == "Phó phòng")
            {
                phucap = 300000;
            }
            return phucap;
        }
        public double TienLinh(NhanVien nv)
        {
            double tienlinh = 0;
            tienlinh = nv.BacLuong * 650000 * NCTL(nv) + PhuCap(nv);
            return tienlinh;
        }
        public ActionResult NhapThongTin()
        {
            return View();
        }
        public ActionResult HienThi(NhanVien nv)
        {
            ViewBag.maNV = nv.MaNV;
            ViewBag.ngayCong = nv.NgayCong;
            ViewBag.tienLinh = TienLinh(nv);
            return View();
        }
    }
}

Bai4/Bài 4.4/Bai4.4/Bai4.4/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("2020600461", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Nhập thông tin", "NhapThongTin", "NhanVien")</li>

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>